import { useTranslate } from '@Shared/translate.js';
const { setBulk } = useTranslate();

setBulk({
    en: {
        'character.select.no.account': 'No account was found, restart your game',
        'character.select.bad.write': 'Failed to update, rejoin the server',
        'character.select.bad.character': 'Character does not exist, rejoin server',
        'character.select.first.invalid': 'First name is invalid',
        'character.select.last.invalid': 'Last name is invalid',
        'character.select.invalid.characters': 'Name uses invalid characters',
        'character.select.username.taken': 'Name is unavailable',
        'character.select.character.not.found': 'Character not found, refreshed characters',
        'character.select.submit': 'Submit',
        'character.select.cancel': 'Cancel',
        'character.select.confirm': 'Confirm',
        'character.select.delete': 'Delete',
        'character.select.spawn': 'Spawn',
        'character.select.create': 'Create Character',
        'character.select.no.appearance': 'No Appearance',
        'character.select.confirm.delete': 'Are you sure you want to delete',
        'character.select.first': 'Name / First Name',
        'character.select.last': 'Last Name',
        'character.select.max.characters.reached': 'Max characters reached',
    },
    uk: {
        'character.select.no.account': 'Акаунт не знайдено, перезапустіть гру',
        'character.select.bad.write': 'Не вдалося оновити, знову приєднайтесь до сервера',
        'character.select.bad.character': 'Персонаж не існує, знову приєднайтесь до сервера',
        'character.select.first.invalid': 'Невірне Ім\'я',
        'character.select.last.invalid': 'Невірне Прізвище',
        'character.select.invalid.characters': 'Ім\'я містить недопустимі символи',
        'character.select.username.taken': 'Ім\'я недоступне',
        'character.select.character.not.found': 'Персонаж не знайдено, оновіть персонажів',
        'character.select.submit': 'Створити',
        'character.select.cancel': 'Скасувати',
        'character.select.confirm': 'Підтвердити',
        'character.select.delete': 'Видалити',
        'character.select.spawn': 'Поява',
        'character.select.create': 'Створити персонажа',
        'character.select.no.appearance': 'Немає зовнішності',
        'character.select.confirm.delete': 'Ви впевнені, що хочете видалити',
        'character.select.first': 'Ім\'я',
        'character.select.last': 'Прізвище',
        'character.select.max.characters.reached': 'Досягнуто максимальної кількості символів',
    },
});
